// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinhKhanhTour.CMS.Data;

#nullable disable

namespace VinhKhanhTour.CMS.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    partial class CmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanhTour.Shared.Models.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrlEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudioUrlVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionIt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionJa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionKo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameJa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptIt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptJa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptKo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsScriptZh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pois");
                });

            modelBuilder.Entity("VinhKhanhTour.Shared.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("VinhKhanhTour.Shared.Models.TourStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TourStops");
                });

            modelBuilder.Entity("VinhKhanhTour.Shared.Models.UsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsQrTriggered")
                        .HasColumnType("boolean");

                    b.Property<int>("ListenDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UserLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("UserLongitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("UsageHistories");
                });

            modelBuilder.Entity("VinhKhanhTour.Shared.Models.UserRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
