using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using VinhKhanhTour.CMS.Services;
using VinhKhanhTour.Shared.Data;
using VinhKhanhTour.Shared.Models;

namespace VinhKhanhTour.CMS.Controllers
{
    [ApiController]
    [Route("api/analytics")]
    public class AnalyticsApiController : ControllerBase
    {
        private readonly IAppAnalyticsService _analyticsService;
        private readonly IPoiRepository _poiRepository;

        public AnalyticsApiController(IAppAnalyticsService analyticsService, IPoiRepository poiRepository)
        {
            _analyticsService = analyticsService;
            _poiRepository = poiRepository;
        }

        [HttpGet("overview")]
        public async Task<ActionResult<DashboardOverviewDto>> GetDashboardOverview()
        {
            var overview = await _analyticsService.GetDashboardOverviewAsync();
            return Ok(overview);
        }

        [HttpGet("audit-logs")]
        public async Task<ActionResult<PagedResult<AppAuditLogDto>>> GetAuditLogs([FromQuery] AuditLogFilterDto filter)
        {
            // Set defaults if missing
            if (filter.Page <= 0) filter.Page = 1;
            if (filter.PageSize <= 0) filter.PageSize = 20;

            var result = await _analyticsService.GetAuditLogsAsync(filter);
            return Ok(result);
        }

        [HttpPost("audit-logs")]
        public async Task<IActionResult> RecordAuditLog([FromBody] AppAuditLogDto record)
        {
            if (string.IsNullOrEmpty(record.UserId) || string.IsNullOrEmpty(record.Action))
            {
                return BadRequest("UserId and Action are required fields.");
            }

            await _analyticsService.RecordAuditLogAsync(record.UserId, record.Action, record.Details ?? "");
            return Ok();
        }

        [HttpPost("sync-usage")]
        public async Task<IActionResult> SyncUsageHistory([FromBody] List<UsageHistory> histories)
        {
            if (histories == null || !histories.Any())
            {
                return Ok();
            }

            foreach (var history in histories)
            {
                // To avoid ID conflicts, we clear the ID from the client local DB so it gets generated by CMS DB
                history.Id = 0;
                await _poiRepository.RecordUsageAsync(history);
            }

            return Ok(new { SyncedCount = histories.Count });
        }
    }
}
